<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-leo-g-flores/blob/main/Last_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
np.__version__

'2.0.2'

In [6]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [7]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [8]:
# COMPLETE THIS TASK
np.linspace?

In [9]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

In [10]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [11]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

In [12]:
R = np.random.randn(3,3)
U = np.random.randn(3,3)
R, U

(array([[-0.90883727,  1.94123808,  1.42807195],
        [ 0.21070974, -0.52479596, -0.60967958],
        [-1.48252132,  0.28120763,  0.32109548]]),
 array([[ 0.91082956,  0.15867988, -1.81631238],
        [-0.0280471 , -0.01853997,  1.34550989],
        [ 0.39659561, -1.04893477,  1.37759086]]))

In [28]:
# COMPLETE THIS TASK
# Decompose a 5x5 random matrix into (real) symmetric and antisymmetric parts.
W = np.random.randn(5,5)
W

W = 0.5 * (W + W.T)

W = 0.5 * (W - W.T)

In [32]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

In [33]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A @ B

array([[ 70, 100],
       [150, 220]])

In [37]:
np.matmul?

In [38]:
np.dot?

`matmul` differs from `dot` in two important ways:

- Multiplication by scalars is not allowed, use `*` instead.
- Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature ``(n,k),(k,m)->(n,m)``

a = np.ones([9, 5, 7, 4])

c = np.ones([9, 5, 4, 3])

np.dot(a, c).shape

(9, 5, 7, 9, 5, 3)

np.matmul(a, c).shape

(9, 5, 7, 3)

n is 7, k is 4, m is 3

In [43]:
# example of .matmul
a = np.ones([1, 2])
c = np.ones([1, 2])
# To perform matrix multiplication, transpose one of the arrays
a @ c.T

array([[2.]])