<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-leo-g-flores/blob/main/Last_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
np.__version__

'2.0.2'

In [37]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [38]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [39]:
# COMPLETE THIS TASK
np.linspace?

In [40]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

In [41]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [42]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

In [43]:
R = np.random.randn(3,3)
U = np.random.randn(3,3)
R, U

(array([[ 1.206515  ,  0.14254481,  0.03775637],
        [ 0.07145622, -0.6260867 , -0.5552064 ],
        [ 0.77673847, -0.14772817, -1.34561136]]),
 array([[-0.44264996,  0.38232492, -0.36629065],
        [ 0.65478712,  0.41836791,  0.62346761],
        [ 1.68981803, -2.59405324, -0.64036965]]))

In [44]:
# COMPLETE THIS TASK
# Decompose a 5x5 random matrix into (real) symmetric and antisymmetric parts.
W = np.random.randn(5,5)
W

W = 0.5 * (W + W.T)

W = 0.5 * (W - W.T)

In [45]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

In [46]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A @ B

array([[ 70, 100],
       [150, 220]])

In [47]:
np.matmul?

In [48]:
np.dot?

`matmul` differs from `dot` in two important ways:

- Multiplication by scalars is not allowed, use `*` instead.
- Stacks of matrices are broadcast together as if the matrices were elements, respecting the signature ``(n,k),(k,m)->(n,m)``

a = np.ones([9, 5, 7, 4])

c = np.ones([9, 5, 4, 3])

np.dot(a, c).shape

(9, 5, 7, 9, 5, 3)

np.matmul(a, c).shape

(9, 5, 7, 3)

n is 7, k is 4, m is 3

In [49]:
# example of .matmul
a = np.ones([1, 2])
c = np.ones([3, 2])
# To perform matrix multiplication, transpose one of the arrays
a @ c.T

array([[2., 2., 2.]])

In [50]:
# example of .dot
b = np.ones([5, 6])
d = np.ones([7, 6])
np.dot(b, d.T)

array([[6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6.]])

In [51]:
import math

In [54]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

173 ms ± 20 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%%timeit
y_vec = np.sin(xs)

10.7 ms ± 37.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# COMPLETE THIS TASK
# Ask gemini about %%timeit

In [59]:
# COMPLETE THIS TASK (vectorized function total energy of harmonic oscillator)
def total_energy(m, v, k, x):
    K = 0.5 * m * v**2
    U = 0.5 * k * x**2
    T = K + U
    return T

In [60]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))